### ISSUE TITLE
Bug Report: p455w0rd's Things / Actually Additions interaction

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#429]
If you try to place a p455w0rd's Things Emerald Infused Carbon Jetplate (with or without Jet Pack upgrade) into an Actually Additions Item Repairer the client immediately crashes. This does not occur with the p455w0rd's Things Carbon Jet Pack. After the client is restarted the item appears to be safely deposited into the Repairers output and does not crash taking it out.

```
java.lang.ArithmeticException: / by zero
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityItemRepairer.getItemDamageToScale(TileEntityItemRepairer.java:129)
	at de.ellpeck.actuallyadditions.mod.inventory.gui.GuiRepairer.func_146976_a(GuiRepairer.java:75)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at de.ellpeck.actuallyadditions.mod.inventory.gui.GuiRepairer.func_73863_a(GuiRepairer.java:55)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by p455w0rd** [comment]
you shouldn't be able to repair either of these items..i don't really consider this a bug as these items don't take damage so there is no need to repair them..

**Comment by Aedda** [comment]
The Item Repairer checks if the item inserted is valid for repairing. It calls item.isRepairable() and does not proceed if false and not also in its white list. There appear to be several ways to resolve this, the most basic being overriding isRepairable() and returning false. setNoRepair() can also be called on the item.

The canRepair boolean is set to true by default in the Item class and is used in isRepairable() along with the boolean result of isDamageable() which in turn checks if the item has a maxDamage exceeding 0 which I do not see set to a non-zero value except for the Carbon Shield so maxDamage must be getting set to a non-zero value higher up.

In any case the client is crashing because of this. One could use the argument, "then the user shouldn't try that again" but isn't that true of most bugs?

**Comment by p455w0rd** [comment]
![ ... ](https://puu.sh/svwmj/be7c96da69.png) has always been this way...ItemEmeraldCarbonArmor and the jetplate extend ItemTeslaArmor which has this set..so you are incorrect

**Comment by Aedda** [comment]
I agree. I was just looking at that fact, we should place some blame on Mojang for having more than one way to test something so simple also maybe. I'll make an issue with AA about not checking both methods.
