### ISSUE TITLE
Bug Report: AppEng & vanilla Recipe Book

### ISSUE THREAD

**Issue by DoctorFTB** [MinecraftModDevelopment/MMD-Dev-Server#565]
After click with sword from silent gems (other mods not tested) - I have kick (A fatal error has occurred, this connection is terminated). In console:
[18:03:47] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: appeng.recipes.helpers.PartShapedCraftingFactory@57d30bd7 Name: appliedenergistics2:tools/paintballs_yellow
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: appeng.recipes.helpers.PartShapedCraftingFactory@57d30bd7 Name: appliedenergistics2:tools/paintballs_yellow
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:52) ~[qj.class:?]
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:34) ~[qj.class:?]
	at net.minecraft.client.gui.recipebook.RecipeList.func_194214_a(SourceFile:27) ~[bnq.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.lambda$handleRecipeBook$2(NetHandlerPlayClient.java:1485) ~[brx.class:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.client.network.NetHandlerPlayClient.func_191980_a(NetHandlerPlayClient.java:1483) ~[brx.class:?]
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:39) ~[jr.class:?]
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:12) ~[jr.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more

**Comment by Morpheus1101** [comment]
This issue is fixed in 1.12.2 version as of December
